apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-to-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-to-pdf
  template:
    metadata:
      labels:
        app: doc-to-pdf
    spec:
      containers:
      - name: doc-to-pdf
        image: doc-to-pdf
        ports:
        - containerPort: 5000
